import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  // Declaration
  const router = useRouter();
  // function
  const getLogin = () => {
    var key = localStorage.getItem("loginKey");
    console.log(key)

    if(key === null){
      router.push("/login")
    }
  }

  useEffect(() => {
    getLogin();
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Beranda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}
