import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useRouter } from 'next/router'
import { useEffect } from 'react';
import { qcount, vote } from '../assets';
import styles from '../styles/Home.module.css'

export default function Home() {
  // Declaration
  const router = useRouter();
  // function
  const getLogin = () => {
    var key = localStorage.getItem("loginKey");
    console.log(key)

    if (key === null) {
      router.push("/login")
    } else if (key == 'admin') {
      router.push("/admin/")
    }
  }

  useEffect(() => {
    getLogin();
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Beranda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type='image/png' href="/logo.png" />
      </Head>

      <div>
        <div className={styles.bg}></div>
        <div className={styles.bg + styles.bg2}></div>
        <div className={styles.bg + styles.bg3}></div>
        <div className={styles.content} >
          <h1>Welcome To Evoting HIMABO 2022</h1>
        </div>
        <div className={styles.right2}>
          <Link href={"/login"}>
            <button className='btn btn-outline-danger'>Logout</button>
          </Link>
        </div>
        <div className={styles.centeringContent}>
          <div className={styles.boxPemilihan2}>
            <div className='row'>
              <div className='col-md'>
                <Link href={"/voting"}>
                  <button className='btn btn-outline-primary'><Image src={vote} height={100} width={100} /><br />Voting</button>
                </Link>
              </div>
              <div className='col-md'>
                <Link href={"/quick-count"}>
                  <button className='btn btn-outline-warning'><Image src={qcount} height={100} width={100} /><br />Quick Count</button>
                </Link>
              </div>
              <div className='col-md'>
                <Link href={"/profil-calon"}>
                  <button className='btn btn-outline-success'><Image src={"/user2.png"} height={100} width={100} /><br />Profil Calon</button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  )
}
